#!/bin/bash
updatenag="There are updates for the following projects: "
for project in $(find * -maxdepth 0 -type d); do
	echo "-----------------------------------";
	echo "Syncing $project";
	echo "-----------------------------------";
	cd "$project";
	sync=$(git pull origin);
	if [ $? -eq 0 ]; then
		if [[ $sync != *"Already up"* ]]; then
			updatenag+="$project "
		else
			last=$(git log | grep "Date:" | head -n 1);
			last=$(echo ${last#D*:} | cut -d " " -f 1,2,3,4);
			echo "Last updated on $last";
		fi
	fi
	echo "";
	cd ..;
done
echo $updatenag;
